name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup Poetry
      uses: dschep/install-poetry-action@v1.3
      with:
        version: 1.0.0
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make verify
    - name: Run tests
      run: |
        make test
